[package]
name = "svabresp"
version = "0.1.0"
edition = "2024"

[dependencies]
prism-model = { workspace = true }
prism-parser = { workspace = true }
probabilistic-models = { workspace = true }
probabilistic-model-algorithms = { workspace = true }
probabilistic-properties = { workspace = true }
tiny-pmc = { workspace = true }
prism-model-builder = { workspace = true }
num-bigint = "0.4.6"
chumsky = "1.0.0-alpha.8"
num-rational = "0.4.2"
num-traits = "0.2.19"
rand = "0.10.0-rc.6"
log = "0.4.29"